-- ============================================
-- SEED DATA WITHOUT USER PROFILES
-- ============================================
-- This script creates job listings WITHOUT requiring users to exist first
-- Use this if you want to seed jobs before creating user accounts
-- ============================================

DO $$
DECLARE
  job_count INTEGER;
BEGIN
  -- Insert job listings (no user dependencies)
  INSERT INTO public.job_listings (
    id, title, company, location_address, location_city, location_district,
    salary_min, salary_max, salary_currency, salary_period,
    description, summary, requirements, benefits, work_arrangement,
    accessibility_level, accessibility_details, application_url,
    deadline, source, source_id, is_active, created_at, updated_at
  ) VALUES
  (
    gen_random_uuid(),
    'Software Developer',
    'PT Teknologi Indonesia',
    'Jl. Sudirman No. 52',
    'Jakarta Pusat',
    'Sudirman',
    10000000,
    15000000,
    'IDR',
    'monthly',
    'Kami mencari Software Developer berpengalaman untuk mengembangkan aplikasi web dan mobile. Kandidat akan bekerja dengan teknologi modern seperti React, Node.js, dan cloud services.',
    'Posisi: Software Developer di PT Teknologi Indonesia. Gaji: 10 hingga 15 juta Rupiah per bulan. Lokasi: Sudirman, Jakarta Pusat. Aksesibilitas: Tinggi - Dukungan screen reader lengkap, remote work option.',
    ARRAY['Minimal 3 tahun pengalaman', 'Menguasai JavaScript/TypeScript', 'Memahami React dan Node.js', 'Pengalaman dengan database'],
    ARRAY['BPJS Kesehatan & Ketenagakerjaan', 'Tunjangan transport', 'Remote work option', 'Training budget'],
    'hybrid',
    'high',
    ARRAY['JAWS screen reader compatible', 'Flexible work hours', 'Remote work option available', 'Accessible development tools'],
    'https://example.com/apply/software-dev',
    NOW() + INTERVAL '30 days',
    'karirhub',
    'kh-software-dev-001',
    true,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Data Analyst',
    'PT Analytics Solutions',
    'Jl. Thamrin No. 100',
    'Jakarta Pusat',
    'Thamrin',
    12000000,
    18000000,
    'IDR',
    'monthly',
    'Mencari Data Analyst untuk menganalisis data bisnis dan memberikan insights strategis. Kandidat akan bekerja dengan tim data science dan business intelligence.',
    'Posisi: Data Analyst di PT Analytics Solutions. Gaji: 12 hingga 18 juta Rupiah per bulan. Lokasi: Thamrin, Jakarta Pusat. Aksesibilitas: Tinggi - Dukungan screen reader, accessible tools.',
    ARRAY['Minimal 2 tahun pengalaman', 'Menguasai SQL dan Python', 'Memahami data visualization', 'Kemampuan analitis yang kuat'],
    ARRAY['BPJS', 'Bonus performa', 'Remote work option', 'Data science training'],
    'hybrid',
    'high',
    ARRAY['Screen reader support', 'Accessible data tools', 'Flexible hours'],
    'https://example.com/apply/data-analyst',
    NOW() + INTERVAL '25 days',
    'dnetwork',
    'dn-data-analyst-001',
    true,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'UI/UX Designer',
    'PT Design Studio',
    'Jl. Senopati No. 8',
    'Jakarta Selatan',
    'Senayan',
    9000000,
    16000000,
    'IDR',
    'monthly',
    'Kami mencari UI/UX Designer yang berpengalaman dalam merancang antarmuka yang aksesibel dan user-friendly. Kandidat akan bekerja dengan tim product dan development.',
    'Posisi: UI/UX Designer di PT Design Studio. Gaji: 9 hingga 16 juta Rupiah per bulan. Lokasi: Senayan, Jakarta Selatan. Aksesibilitas: Tinggi - Remote work, accessible design tools.',
    ARRAY['Minimal 3 tahun pengalaman', 'Menguasai Figma atau Adobe XD', 'Memahami prinsip aksesibilitas', 'Portfolio yang kuat'],
    ARRAY['BPJS', 'Remote work', 'Design tools subscription', 'Conference budget'],
    'remote',
    'high',
    ARRAY['Fully remote', 'Accessible design tools', 'Screen reader compatible workflow'],
    'https://example.com/apply/uiux-designer',
    NOW() + INTERVAL '20 days',
    'kerjabilitas',
    'kj-uiux-001',
    true,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Frontend Developer',
    'PT Digital Solutions',
    'Jl. Gatot Subroto No. 88',
    'Jakarta Selatan',
    'Kuningan',
    12000000,
    18000000,
    'IDR',
    'monthly',
    'Kami mencari Frontend Developer berpengalaman untuk mengembangkan aplikasi web modern menggunakan React dan TypeScript. Kandidat akan bekerja dalam tim yang dinamis dan inovatif.',
    'Posisi: Frontend Developer di PT Digital Solutions. Gaji: 12 hingga 18 juta Rupiah per bulan. Lokasi: Kuningan, Jakarta Selatan. Aksesibilitas: Tinggi - Dukungan screen reader lengkap, remote work option.',
    ARRAY['Minimal 3 tahun pengalaman', 'Menguasai React, TypeScript, CSS', 'Memahami state management (Redux, Zustand)', 'Pengalaman dengan testing frameworks'],
    ARRAY['BPJS Kesehatan & Ketenagakerjaan', 'Tunjangan transport', 'Remote work option', 'Training budget'],
    'hybrid',
    'high',
    ARRAY['JAWS screen reader compatible', 'Flexible work hours', 'Remote work option available', 'Accessible development tools'],
    'https://example.com/apply/frontend-dev',
    NOW() + INTERVAL '30 days',
    'karirhub',
    'kh-frontend-001',
    true,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Backend Developer',
    'PT Tech Innovation',
    'Jl. Thamrin No. 100',
    'Jakarta Pusat',
    'Thamrin',
    10000000,
    15000000,
    'IDR',
    'monthly',
    'Mencari Backend Developer untuk mengembangkan API dan sistem backend yang scalable. Kandidat akan bekerja dengan teknologi modern seperti Node.js, Python, atau Go.',
    'Posisi: Backend Developer di PT Tech Innovation. Gaji: 10 hingga 15 juta Rupiah per bulan. Lokasi: Thamrin, Jakarta Pusat. Aksesibilitas: Sedang - Dukungan screen reader tersedia.',
    ARRAY['Minimal 2 tahun pengalaman', 'Menguasai Node.js atau Python', 'Memahami database (PostgreSQL, MongoDB)', 'Pengalaman dengan RESTful API'],
    ARRAY['BPJS', 'Bonus performa', 'Flexible hours'],
    'on-site',
    'medium',
    ARRAY['Screen reader support available', 'Flexible hours'],
    'https://example.com/apply/backend-dev',
    NOW() + INTERVAL '25 days',
    'dnetwork',
    'dn-backend-001',
    true,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Product Manager',
    'PT Startup Indonesia',
    'Jl. Senopati No. 8',
    'Jakarta Selatan',
    'Senayan',
    15000000,
    25000000,
    'IDR',
    'monthly',
    'Kami mencari Product Manager yang berpengalaman untuk memimpin pengembangan produk digital. Kandidat akan bekerja dengan tim cross-functional dan stakeholders.',
    'Posisi: Product Manager di PT Startup Indonesia. Gaji: 15 hingga 25 juta Rupiah per bulan. Lokasi: Senayan, Jakarta Selatan. Aksesibilitas: Tinggi - Remote work, flexible hours.',
    ARRAY['Minimal 5 tahun pengalaman', 'Memahami product development lifecycle', 'Kemampuan komunikasi dan leadership', 'Pengalaman dengan agile methodology'],
    ARRAY['BPJS', 'Equity options', 'Remote work', 'Unlimited leave'],
    'remote',
    'high',
    ARRAY['Fully remote', 'Flexible work hours', 'Screen reader compatible tools', 'Async communication'],
    'https://example.com/apply/pm',
    NOW() + INTERVAL '20 days',
    'kerjabilitas',
    'kj-pm-001',
    true,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'QA Engineer',
    'PT Quality Assurance',
    'Jl. Rasuna Said No. 5',
    'Jakarta Selatan',
    'Kuningan',
    8000000,
    12000000,
    'IDR',
    'monthly',
    'Mencari QA Engineer untuk melakukan testing dan memastikan kualitas produk. Kandidat akan bekerja dengan tim development untuk mengidentifikasi dan memperbaiki bugs.',
    'Posisi: QA Engineer di PT Quality Assurance. Gaji: 8 hingga 12 juta Rupiah per bulan. Lokasi: Kuningan, Jakarta Selatan. Aksesibilitas: Sedang - Dukungan screen reader tersedia.',
    ARRAY['Minimal 2 tahun pengalaman', 'Memahami testing methodologies', 'Pengalaman dengan automation testing', 'Kemampuan analitis yang baik'],
    ARRAY['BPJS', 'Training opportunities'],
    'hybrid',
    'medium',
    ARRAY['Screen reader support', 'Flexible hours'],
    'https://example.com/apply/qa',
    NOW() + INTERVAL '15 days',
    'karirhub',
    'kh-qa-001',
    true,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'DevOps Engineer',
    'PT Cloud Services',
    'Jl. Sudirman No. 52',
    'Jakarta Pusat',
    'Sudirman',
    13000000,
    20000000,
    'IDR',
    'monthly',
    'Kami mencari DevOps Engineer untuk mengelola infrastruktur cloud dan CI/CD pipelines. Kandidat akan bekerja dengan teknologi seperti AWS, Docker, Kubernetes.',
    'Posisi: DevOps Engineer di PT Cloud Services. Gaji: 13 hingga 20 juta Rupiah per bulan. Lokasi: Sudirman, Jakarta Pusat. Aksesibilitas: Tinggi - Remote work option, accessible tools.',
    ARRAY['Minimal 3 tahun pengalaman', 'Menguasai AWS atau GCP', 'Memahami Docker dan Kubernetes', 'Pengalaman dengan CI/CD tools'],
    ARRAY['BPJS', 'Remote work', 'Cloud certification support'],
    'remote',
    'high',
    ARRAY['Fully remote option', 'Screen reader compatible CLI tools', 'Flexible work hours'],
    'https://example.com/apply/devops',
    NOW() + INTERVAL '28 days',
    'dnetwork',
    'dn-devops-001',
    true,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Full Stack Developer',
    'PT Web Solutions',
    'Jl. Kuningan No. 12',
    'Jakarta Selatan',
    'Kuningan',
    15000000,
    22000000,
    'IDR',
    'monthly',
    'Mencari Full Stack Developer untuk mengembangkan aplikasi web end-to-end. Kandidat akan bekerja dengan React, Node.js, dan database modern.',
    'Posisi: Full Stack Developer di PT Web Solutions. Gaji: 15 hingga 22 juta Rupiah per bulan. Lokasi: Kuningan, Jakarta Selatan. Aksesibilitas: Tinggi - Remote work, accessible tools.',
    ARRAY['Minimal 4 tahun pengalaman', 'Menguasai React dan Node.js', 'Memahami database design', 'Pengalaman dengan cloud services'],
    ARRAY['BPJS', 'Remote work', 'Tech conference budget', 'Stock options'],
    'hybrid',
    'high',
    ARRAY['Remote work option', 'Screen reader support', 'Flexible hours'],
    'https://example.com/apply/fullstack',
    NOW() + INTERVAL '22 days',
    'karirhub',
    'kh-fullstack-001',
    true,
    NOW(),
    NOW()
  ),
  (
    gen_random_uuid(),
    'Mobile Developer',
    'PT Mobile Apps',
    'Jl. Senayan No. 15',
    'Jakarta Selatan',
    'Senayan',
    11000000,
    17000000,
    'IDR',
    'monthly',
    'Kami mencari Mobile Developer untuk mengembangkan aplikasi iOS dan Android. Kandidat akan bekerja dengan React Native atau Flutter.',
    'Posisi: Mobile Developer di PT Mobile Apps. Gaji: 11 hingga 17 juta Rupiah per bulan. Lokasi: Senayan, Jakarta Selatan. Aksesibilitas: Sedang - Dukungan screen reader tersedia.',
    ARRAY['Minimal 3 tahun pengalaman', 'Menguasai React Native atau Flutter', 'Memahami mobile app architecture', 'Pengalaman dengan app store deployment'],
    ARRAY['BPJS', 'Device allowance', 'App store fees covered'],
    'hybrid',
    'medium',
    ARRAY['Screen reader support', 'Flexible hours'],
    'https://example.com/apply/mobile-dev',
    NOW() + INTERVAL '18 days',
    'dnetwork',
    'dn-mobile-001',
    true,
    NOW(),
    NOW()
  )
  ON CONFLICT (source, source_id) DO UPDATE SET 
    updated_at = NOW(),
    is_active = true;

  SELECT COUNT(*) INTO job_count FROM public.job_listings;
  RAISE NOTICE 'Successfully created/updated job listings. Total jobs: %', job_count;
  
END $$;
